### ISSUE TITLE
配置邮件报错？

### ISSUE THREAD

**Issue by Mr-Oxidation** [jinhucheung/milog#2]
我在email.yml配置了如下配置
```
config/email.ymlproduction:
  address: "smtp.exmail.qq.com"
  port: 465
  domain: "exmail.qq.com"
  authentication: "plain"
  user_name: "oxida@oxida.cn"
  password: "********"
  enable_starttls_auto: true
  openssl_verify_mode: 'none'
```
我注册后无法发送邮件，报错如下：
`Unable to find a browser command. If this is unexpected, Please rerun with environment variable LAUNCHY_DEBUG=true or the '-d' commandline option and file a bug at https://github.com/copiousfreetime/launchy/issues/new`
```
 def new
    @user.generate_activation_digest
    AccountsMailer.active_account(@user).deliver #这一行爆红
    flash[:info] = I18n.t "flash.info.validated_mail"
    redirect_to user_path(@user.username)
  end
```
我使用的是腾讯的企业邮箱，我使用foxmial登陆发送都没问题，我不知道是我配置错误还是其他问题，我已经研究很久了，还是没有解决！

**Comment by Mr-Oxidation** [comment]
@jinhucheung   你好，我按照你的方法，重新拉取和bundle了，可是还是一样的错误，以下为补充的报错信息：
`app/controllers/accounts/activations_controller.rb:12:in `new'`

```
def new
    @user.generate_activation_digest
    AccountsMailer.active_account(@user).deliver #此行出错
    flash[:info] = I18n.t "flash.info.validated_mail"
    redirect_to user_path(@user.username)
  end
```

**Comment by jinhucheung** [comment]
@Mr-Oxidation 嗯嗯， 从错误日志上看，可以发现 

[letter_opener](https://github.com/ryanb/letter_opener) gem 在发送邮件时报错了， 这个 gem 是方便在开发模式测试邮件服务的。 上面的错误原因应该是 milog 运行在没有浏览器的环境， 需要确认下

而 email.yml 是用在生产模式用 SMTP 转发邮件的

**Comment by Mr-Oxidation** [comment]
@jinhucheung 谢谢，我是一个刚学习rails的小白，还是没有搞定，我使用的是Passenger的nginx部署的，使用生产和使用开发都是一样的错误，我已经放弃了

**Comment by Mr-Oxidation** [comment]
@jinhucheung  已经解决，这里放上腾讯企业邮箱的配置，以帮助需要的人：

```
production:
  address: "smtp.exmail.qq.com"
  port: 465
  domain: "xxx.cn" //你的域名
  authentication: "login" 
  user_name: "登录名"
  password: "密码"
  enable_starttls_auto: true
  openssl_verify_mode: 'none'
  ssl: true
```
